name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'docker-compose.yml'

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: foodgram
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      POSTGRES_DB: foodgram
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DEBUG: True
      SECRET_KEY: test-key
      ALLOWED_HOSTS: localhost,127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 backend --exclude migrations,__pycache__ --max-line-length=88

      - name: Run migrations
        run: |
          python backend/manage.py migrate

      - name: Run tests
        run: |
          python backend/manage.py test
